[[main]]
  identifier = "timeline"
  name = "â³ Timeline Post"
  url = "timeline"
  weight = 1

[[main]]
  identifier = "tags"
  name = "ğŸ·ï¸ Tag"
  url = "tags"
  weight = 2

[[main]]
  identifier = "posts"
  name = "âœï¸ Postingan"
  url = "posts"
  weight = 3

[[main]]
  identifier = "about"
  name = "ğŸŒ€ About"
  url = "about"
  weight = 4
